### ISSUE TITLE
Замечание по организации репозитория

### ISSUE THREAD

**Issue by trtpo** [Konikov-Alexandr-450501/Unmindful-house#1]
Александр!
Настоятельно, просто-таки агрессивно, рекомендую не иметь в репозитории одни и те же документы в трёх экземплярах типа corrected, final, etc. Мы потому и используем систему контроля версиями, чтобы иметь версии и их контролировать!!! (Перечитайте, пожалуйста, инфо о том, что такое git, и зачем он нужен).
После того, как закроем этот вопрос, рекомендую структурировать репозиторий, например, чтобы была отдельная папка для документации, отдельная для кода и тд

**Comment by SanyaSKY** [comment]
Спасибо за замечание. Я знаю, что сделал неправильно. Вопрос решён, репозиторий структурирован.
